#!/bin/sh

# PROVIDE: FCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# FCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable FCoin service.
# FCoin_config (path): Set to /usr/local/etc/FCoin.conf by default.
# FCoin_user:  The user account FCoin daemon runs as. It uses 'root' user by default.
# FCoin_group: The group account FCoin daemon runs as. It uses 'wheel' group by default.
# FCoin_datadir (str): Default to "/var/db/FCoin". Base data directory.

. /etc/rc.subr

name=FCoin
rcvar=FCoin_enable

: ${FCoin_enable:=NO}
: ${FCoin_config=/usr/local/etc/FCoin.conf}
: ${FCoin_datadir=/var/db/FCoin}
: ${FCoin_user="root"}
: ${FCoin_group="wheel"}

required_files=${FCoin_config}
command=/usr/local/bin/FCoind
FCoin_chdir=${FCoin_datadir}
pidfile="${FCoin_datadir}/FCoind.pid"
stop_cmd=FCoin_stop
command_args="-conf=${FCoin_config} -datadir=${FCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

FCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${FCoin_datadir}
	[ $? -eq 0 ] && chown -R ${FCoin_user}:${FCoin_group} ${FCoin_datadir}
}

FCoin_prestart()
{
	if [ ! -d "${FCoin_datadir}/." ]; then
		FCoin_create_datadir || return 1
	fi
}

FCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

FCoin_stop()
{
    FCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${FCoin_config} -datadir=${FCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
